---
title: "Lab 10: ANOVA"
author: "Mandy Klehr -- I worked with Jahiya, John, Matt, Heather, Erika, and Bonnie"
date: "11/28/2021"
output:  
  html_document:
    theme: spacelab
    toc: yes
    toc_float: yes
---

# Q1

```{r ANOVA by hand}
rm(list = ls())

rope = read.csv(here("data", "rope.csv"))

rope$rope.type = factor(rope$rope.type)
levels(rope$rope.type)

n_obs = nrow(rope)
n_groups = nrow(aggregate(rope$rope.type, by=list(rope$rope.type), FUN = length))
#n_groups_levels = ncol(factor(rope$rope.type))


#0.05581 or something should be the answer
ss_tot = mean(rope$p.cut)
#we lose one degree of freedom because we estimate a grand mean
df_tot = n_obs - 1

#issues with the below agg_sq_resids code to be worked out 
agg_sq_resids = aggregate(
  x = rope$p.cut, 
  by = list(rope$rope.type),
  FUN = fuction(x) sum((x - mean(x)^2)))
  
ss_within = sum(agg_sq_resids$x)
  #sum agg_sq_resids$x....
#ss_within squared residuals and need to sum them all up, aggregate square residuals? 
df_within = n_obs - n_groups

ss_among = ss_tot - ss_within
df_among = n_groups - 1

ms_within = ss_within / (n_obs - n_groups)
ms_among  = ss_among / (n_groups - 1)

f_ratio = ms_among / ms_within
f_pval = 1 - pf(f_ratio, df_among, df_within)

```


```{r code to be tested against}
# number comparison tolerance
digits_check = 5

# Build the reference model using R functions
fit_1 = lm(p.cut ~ rope.type, data=rope)
anova(fit_1)
anova_fit_1 = anova(fit_1)

# Check degrees of freedom
anova_fit_1$Df == c(df_among, df_within)

# Check sums of squares
round(anova_fit_1$`Sum Sq`, digits = digits_check) == round(c(ss_among, ss_within), digits = digits_check)

# Check mean squares
round(anova_fit_1$`Mean Sq`, digits = digits_check) == round(c(ms_among, ms_within), digits = digits_check)

# Check the F-ratio
round(anova_fit_1$`F value`[1], digits = digits_check) == round(f_ratio, digits = digits_check)

# Check the F test statistic p-value
round(anova_fit_1$`Pr(>F)`[1], digits = digits_check) == round(f_pval, digits = digits_check)
```

# Q2

